# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: sudo apt update
  displayName: 'Update'
- script: sudo apt -y upgrade
  displayName: 
- script: sudo apt install -y python3-pip
  displayName: 'Install pip'

- script: sudo apt-get install git
  displayName: 'Run a multi-line script'